### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by fogha** [yirano/drawFromAHat#13]
While am at it how about you make your documentation a little bit more elaborate

**Comment by yirano** [comment]
Great suggestion Fogha! I started this project before I became more familiar with the culture and custom of Github and never got back to it once I started my other projects. I’ll get to this some time tomorrow afternoon when I’m back on my desk.

**Comment by Fogha** [comment]
Also i have problems understanding where you want your 'X'

**Comment by yirano** [comment]
The 'x' has been implemented already and the basic setup of the README.md file has been revised. :)
