### ISSUE TITLE
Change the list style on the left 

### ISSUE THREAD

**Issue by yirano** [yirano/drawFromAHat#15]
![scrnli_10_1_2019_8-06-17 AM](https://user-images.githubusercontent.com/20312870/65960436-784f6180-e422-11e9-8013-46791647cb78.png)

Get rid of the text-input-like look and give it some flair to match the rest of the page.

**Comment by MohamedYasser97** [comment]
Hi! Can I start working on this issue?

**Comment by yirano** [comment]
Hi @MohamedYasser97! Go for it. :D

**Comment by MohamedYasser97** [comment]
Hey, I've fixed this issue. Do you want me to create a separate branch for this fix or should I just push in the `gh-pages` branch in my fork before starting a PR?
