### ISSUE TITLE
Change the blue highlight border on the text input box

### ISSUE THREAD

**Issue by yirano** [yirano/drawFromAHat#16]
![scrnli_10_1_2019_8-08-52 AM](https://user-images.githubusercontent.com/20312870/65960564-c6fcfb80-e422-11e9-8928-b2475c50a681.png)

Change this default blue highlight border. Get rid of it or make it a different color!

**Comment by MohamedYasser97** [comment]
![image](https://user-images.githubusercontent.com/30673997/66003307-03257000-e4a6-11e9-8205-895056ca3aa7.png)

I'm using Firefox and I can't reproduce this  blue border. Are you sure it's not something browser-related?
