### ISSUE TITLE
Allow multiple names to be input separated by a comma.

### ISSUE THREAD

**Issue by yirano** [yirano/drawFromAHat#18]
This currently takes in one name at a time. 

let's make this more user-friendly by allowing user to input multiple names separated by a comma.

For example, 

If user type in: "Sarah, Aaron, Eric, Peter"

those should count as four separate inputs.

**Comment by MohamedYasser97** [comment]
I can start working on this feature if you're okay with it, it's quite fun actually :D

But first I want to know if this feature will replace the old one or the user will be able to **both** enter names one by one, and enter them separated by commas?

I'll start working on it as soon as I know this.

**Comment by yirano** [comment]
I'd like for the user to have the option to activate this. You can use whatever method to confirm his "option" like a checkbox. Does that make sense? 

I'm really happy that you're having fun @MohamedYasser97! 😀

**Comment by yirano** [comment]
So keep this original feature and allow the user an additional feature.

**Comment by MohamedYasser97** [comment]
Great! on it 😀

**Comment by yirano** [comment]
Thank you @MohamedYasser97!
