### ISSUE TITLE
Allow user to continue picking name until every name has been picked.

### ISSUE THREAD

**Issue by yirano** [yirano/drawFromAHat#19]
Allow the user to _have the option_ to continue picking names until every name has been picked out.

**Comment by MohamedYasser97** [comment]
I think I can start working on this too, I still have time😀

**Comment by yirano** [comment]
@MohamedYasser97 Before you start on this next one, could I ask if you've registered for Hacktoberfest2019?

**Comment by yirano** [comment]
This would be your fourth pull, and if you were registered you'll be meeting the requirements for their coveted shirt after this!

**Comment by yirano** [comment]
**Also to add to this further,

allow the names to be displayed in the order that it was picked to the right side of the page.**

**Comment by MohamedYasser97** [comment]
@yirano Indeed I've registered for Hacktoberfest2019 but this would be my third PR not the 4th. However, I still want to help after my 4th PR. Before this one I've only made one PR in 2017 which I don't even remember doing so this project is my first **real** contribution to anything 😀

**Comment by yirano** [comment]
@MohamedYasser97, ah, forgive me. You've just been working so fast that I'm getting ahead of myself. Well I'm a little jealous! I haven't started a single PR yet. 😆

**Comment by MohamedYasser97** [comment]
@yirano You just need to dig a little deeper for sad abandoned projects 😂. Anyway I can't thank you enough because now I'm getting the hang of all of this contribution routine.

**Comment by yirano** [comment]
You kidding me? I can't thank YOU enough!
